### ISSUE TITLE
My PR#1 broke this middleware

### ISSUE THREAD

**Issue by Cellane** [skelpo/APIErrorMiddleware#3]
I’m really sorry but it seems that my PR #1 actually did more harm than good in the end 😢 It seems that the latest version is actually not compilable at this moment.

I noticed today that the latest version no longer compiles because the updated version of the `ModelNotFound` specialization now explicitly references a type defined not in Vapor itself, but in Fluent package (namely `FluentError`). The original motivation behind the PR was not just to replace the stringly-typed check (which would’ve been fine), but if I remember correctly, the main issue was that `Error` no longer has publicly accessible `identifier` field, making the previous code also not functional.

I think there’s a couple of approaches how to solve this:

1. Add explicit dependency of this package to Fluent (but as we talked with Caleb on Discord, that might not be the best approach)
2. Remove the `ModelNotFound` specialization and leave it up to Vapor projects to implement it
3. Replace the `wrappingError.rootCause is FluentError` with the only other way I can think of, `wrappingError.rootCause.debugDescription.contains("FluentError.modelNotFound")` but oh my gosh, does that feel dirty (and it will probably be also pretty slow)
4. Figure a way how to optionally compile the `ModelNotFound` only if Fluent is also included

Apologies one more time for breaking your project!

**Comment by Cellane** [comment]
Fourth solution (IMO the prettiest and cleanest) is now submitted as PR #4. Let me know if you like this approach!

**Comment by proggeramlug** [comment]
Fixed with PR #4 !
